### ISSUE TITLE
Modificar el path de los personajes principales

### ISSUE THREAD

**Issue by juanppdev** [intentodepirata/api-dragonball#2]
Podrías modificar el path de los personajes principales?. Ya que cuando haces una petición a la api las imágenes no salen, y por ahi ya vi cual es el problema y es que cuando hiciste la migración solo les pusiste http y no htpps, y es por eso que las imágenes no se ven, muchas gracias

**Comment by intentodepirata** [comment]
Thank you very much, it is already modified. All the best
